name: My first pipeline
on:
  push:
    branches:
      - main


jobs:
  valiadate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt -
      - run: echo "This is my second step"
  plan:
    needs: valiadate
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is from plan stage"
  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is from apply stage"